[build]
  # Jekyll build command
  command = "bundle exec jekyll build"
  
  # Publish directory (Jekyll output)
  publish = "_site"
  
  # Functions directory for serverless functions
  functions = "_functions"

[build.environment]
  # Jekyll environment
  JEKYLL_ENV = "production"
  
  # Ruby version (if needed)
  RUBY_VERSION = "3.0"

# Redirects for the API function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle SPA routing (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers for API functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
